# Generated by Django 3.2.5 on 2022-05-30 18:15

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BlogsModel',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('title', models.CharField(max_length=512)),
                ('subtitle', models.TextField()),
                ('liked_by', models.UUIDField(editable=False, null=True, unique=True)),
                ('background', models.ImageField(upload_to='')),
                ('create_date', models.DateTimeField(auto_now=True)),
                ('publish_date', models.DateTimeField(blank=True, null=True)),
                ('person', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='CategoriesModel',
            fields=[
                ('rating', models.PositiveIntegerField(default=0)),
                ('type_blog', models.CharField(choices=[('VD', 'Video Blog'), ('TX', 'Text Blog'), ('AU', 'Podcast Blog'), ('VR', 'Virtual Blog'), ('OT', 'Other Blog')], max_length=2)),
                ('blog', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='blog_app.blogsmodel')),
            ],
        ),
        migrations.CreateModel(
            name='CommentsModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.UUIDField()),
                ('comment', models.TextField(null=True)),
                ('create_date', models.DateTimeField(auto_now=True)),
                ('approved_comment', models.BooleanField(default=False)),
                ('blog', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='blog_app.blogsmodel')),
                ('comment_comment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='blog_app.commentsmodel')),
            ],
        ),
        migrations.CreateModel(
            name='BlogSectionsModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('1', 'total'), ('2', '2:1'), ('3', '1:2'), ('4', '1:1:1')], max_length=1)),
                ('content', models.TextField(null=True)),
                ('blog', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='blog_app.blogsmodel')),
            ],
        ),
        migrations.CreateModel(
            name='BlogSectionImagesModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(null=True, upload_to='')),
                ('blog_section', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='blog_app.blogsectionsmodel')),
            ],
        ),
    ]
