# Generated by Django 3.2.5 on 2022-05-30 21:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog_app', '0002_rename_person_blogsmodel_author'),
    ]

    operations = [
        migrations.RenameField(
            model_name='blogsmodel',
            old_name='author',
            new_name='user',
        ),
    ]
